theme: jekyll-theme-cayman
title: "Neuromorphic Intelligence: From Algorithm to System"
date: Jan. 26 or 27, 2026
location: Singapore
description: part of the 40th AAAI Conference on Artificial Intelligence (AAAI) 2026
plugins:
  - jekyll-sitemap
